te_d: sketch
tpath: examples/tasks/task_pacs_aug.py
bs: 32
model: diva
trainer: fbopt
gamma_y: 1.0
ini_setpoint_ratio: 0.99
str_diva_multiplier_type: gammad_recon
coeff_ma_output_state: 0.1
coeff_ma_setpoint: 0.9
exp_shoulder_clip: 5
mu_init: 0.000001
k_i_gain_ratio: 0.5
mu_clip: 10
epos: 1000
epos_min: 200
npath: examples/nets/resnet50domainbed.py
npath_dom: examples/nets/resnet50domainbed.py
es: 2
lr: 0.00005
zx_dim: 0
zy_dim: 64
zd_dim: 64
force_setpoint_change_once: True
