#!/bin/bash
# sphinx-quickstart
cd docs
pip install -r requirements.txt
sphinx-apidoc -f -o . ../domainlab  # output path is current . directory (docs), module path
make clean
make html
# under docs directory, there is a empty html which point to the html generated by sphinx

