#!/bin/bash
# sphinx-quickstart
git checkout master
git pull
git checkout doc
git pull  # get latest version of doc"
git merge master -m "merge master"

cd docs
pip install -r requirements.txt
sphinx-apidoc -f -o . ../domainlab  # output path is current . directory (docs), module path
make clean
make html
mkdir -p build/html/figs
cp ./*.md build/html/
mkdir -p build/html/figs
cp -r ./figs/* build/html/figs
# under docs directory, there is a empty html which point to the html generated by sphinx

