mode: grid

output_dir: zoutput/benchmarks/benchmark_irm_erm

sampling_seed: 0
startseed: 0
endseed: 2

test_domains:
  - sketch

domainlab_args:
  tpath: examples/tasks/task_pacs_aug.py
  dmem: False
  lr: 5e-5
  epos: 500
  epos_min: 10
  es: 5
  bs: 32
  san_check: False
  npath: examples/nets/resnet50domainbed.py
  npath_dom: examples/nets/resnet50domainbed.py
  zx_dim: 0
  zy_dim: 64
  zd_dim: 64




Shared params:
  nb4reg_over_task_ratio:
    distribution: categorical   # name of the distribution
    datatype: int
    values:                     # concrete values to choose from
      - 0
      - 1
      - 100
      
  ini_setpoint_ratio:
    min: 0.5
    max: 0.99
    num: 2
    step: 0.05
    distribution: uniform

  k_i_gain:
    min: 0.0001
    max: 0.01
    num: 2
    step: 0.0001
    distribution: uniform

  gamma_reg:
    min: 0.01
    max: 1e4
    num: 10
    distribution: loguniform


# Test fbopt with different hyperparameter configurations

irm_erm:
  model: erm
  trainer: irm
  shared:
    - gamma_reg
    - nb4reg_over_task_ratio

irm_erm_dep_dom:
  model: erm
  trainer: irmsepdom
  shared:
    - gamma_reg
    - nb4reg_over_task_ratio
