# test benchmark config.
mode: grid
test_domains:
  - 3
  - 0

output_dir: zoutput/benchmarks/mnist_benchmark_grid

startseed: 0
endseed: 2  # currently included


Shared params:
  zy_dim:
    min: 32
    max: 96
    step: 32
    distribution: uniform
    num: 2
    datatype: int


domainlab_args:
  # Domainlab arguments passed to each task.
  # task specific arguments take precedence.
  ## dataset
  task: mnistcolor10
  tr_d: [1, 2, 4]
  dmem: False
  lr: 0.001
  epos: 2
  es: 5
  bs: 64
  nname: conv_bn_pool_2
  san_check: True
  gamma_y: 50000


method_diva:  # name
  aname: diva
  zx_dim: 0
  zd_dim: 32
  shared:
    - zy_dim
  nname_dom: conv_bn_pool_2

  hyperparameters:
    gamma_d:
      min: 1e4
      max: 1e6
      step: 10_000
      distribution: loguniform
      datatype: float
      num: 2

method_hduva:  # name
  aname: hduva

  nname_topic_distrib_img2topic: conv_bn_pool_2
  nname_encoder_sandwich_layer_img2h4zd: conv_bn_pool_2
  shared:
    - zy_dim
  zx_dim: 0
  zd_dim: 32
