mode: grid

output_dir: zoutput/benchmarks/benchmark_fbopt

sampling_seed: 0
startseed: 0
endseed: 2

test_domains:
  - 3
  - 0


domainlab_args:
  task: mnistcolor10
  tr_d: [1, 2]
  dmem: False
  lr: 0.001
  epos: 500
  es: 100
  bs: 64
  zx_dim: 0
  gamma_d: 1.0
  nname: conv_bn_pool_2
  nname_dom: conv_bn_pool_2
  nname_topic_distrib_img2topic: conv_bn_pool_2
  nname_encoder_sandwich_layer_img2h4zd: conv_bn_pool_2
  san_check: False
  exp_shoulder_clip: 10
  mu_clip: 1000_000
  coeff_ma: 0.5
  no_tensorboard: False



Shared params:
  ini_setpoint_ratio:
    min: 0.9
    max: 0.99
    num: 3
    step: 0.05
    distribution: uniform

  k_i_gain:
    min: 0.0001
    max: 0.01
    num: 2
    step: 0.0001
    distribution: uniform

  init_mu4beta:
    min: 0.01
    max: 1.0
    num: 5
    distribution: uniform

  gamma_y:
    min: 1
    max: 1e6
    num: 3
    step: 100
    distribution: loguniform

  zy_dim:
    min: 32
    max: 96
    num: 2
    step: 32
    distribution: uniform
    datatype: int

  zd_dim:
    min: 32
    max: 96
    num: 2
    step: 32
    distribution: uniform
    datatype: int



# Test fbopt with different hyperparameter configurations

diva_fbopt:
  aname: diva
  trainer: fbopt

  shared:
    - ini_setpoint_ratio
    - k_i_gain
    - init_mu4beta
    - gamma_y
    - zx_dim
    - zy_dim
    - zd_dim

erm:
  aname: deepall
