# test benchmark config.

mode: grid

test_domains:
  - sketch

output_dir: zoutput/benchmarks/pacs_benchmark_grid

startseed: 0
endseed: 5  # currently included


domainlab_args:
  tpath: examples/tasks/task_pacs_path_list.py
  dmem: False
  lr: 5e-5
  epos: 500
  es: 1
  bs: 32
  npath: examples/nets/resnet50domainbed.py
  npath_topic_distrib_img2topic: examples/nets/resnet50domainbed.py
  npath_encoder_sandwich_layer_img2h4zd: examples/nets/resnet50domainbed.py
  san_check: True


Shared params:
  gamma_y:
    min: 1e4
    max: 1e6
    step: 100
    distribution: loguniform
    num: 2

  gamma_d:
    min: 1e4
    max: 1e6
    step: 100
    distribution: loguniform
    num: 1

  zx_dim:
    min: 0
    max: 96
    step: 32
    distribution: uniform
    datatype: int
    num: 1

  zy_dim:
    min: 32
    max: 96
    step: 32
    distribution: uniform
    datatype: int
    num: 1

  zd_dim:
    min: 32
    max: 96
    step: 32
    distribution: uniform
    datatype: int
    num: 1

  gamma_reg:
    min: 0.01
    max: 10
    step: 0.1
    distribution: loguniform
    num: 2

  # Total number of epochs for contrastive loss
  epochs_ctr:
    min: 2
    max: 10
    step: 1
    distribution: uniform
    datatype: int
    num: 2

  # Number of epochs before updating the match tensor
  epos_per_match_update:
    min: 1
    max: 20
    step: 1
    distribution: uniform
    datatype: int
    num: 2

  # factor to magnify cosine similarity
  tau:
    min: 0.01
    max: 1
    distribution: loguniform
    num: 1


diva:
  aname: diva
  shared:
    - gamma_y
    - gamma_d
    - zx_dim
    - zy_dim
    - zd_dim


hduva:  # name
  aname: hduva
  zx_dim: 0
  shared:
    - gamma_y
    - zy_dim
    - zd_dim


matchdg:  # name
  aname: matchdg
  shared:
    - gamma_reg
    - epochs_ctr
    - epos_per_match_update
    - tau


jigen:  # name
  aname: jigen
  grid_len: 3
  shared:
    - gamma_reg

  hyperparameters:
    # number of permutations
    nperm:
      distribution: categorical
      values:
        - 30
        - 31
        - 100
      datatype: int
      num: 1

    # probability of permutating the tiles of an image, pperm = 0 -> pure classification
    pperm:
      min: 0.1
      max: 0.5
      step: 0.1
      distribution: uniform
      num: 2


dann:
  aname: dann
  shared:
    - gamma_reg


erm:
  aname: deepall


dial:
  aname: deepall
  trainer: dial
  shared:
    - gamma_reg

  hyperparameters:
    dial_steps_perturb:
      min: 1
      max: 10
      step: 1
      distribution: uniform
      num: 2

    dial_noise_scale:
      min: 0.00001
      max: 0.1
      distribution: loguniform
      num: 2

    dial_epsilon:
      min: 0.001
      max: 0.01
      distribution: loguniform
      num: 1


mldg:
  aname: deepall
  trainer: mldg
  shared:
    - gamma_reg


hduva_matchdg:
  aname: matchhduva
  zx_dim: 0
  shared:
    - gamma_y
    - zy_dim
    - zd_dim
    - gamma_reg
    - epochs_ctr
    - epos_per_match_update
    - tau


diva_dial:
  aname: diva
  trainer: dial
  shared:
    - gamma_y
    - gamma_d
    - zx_dim
    - zy_dim
    - zd_dim
    - gamma_reg


  hyperparameters:
    dial_steps_perturb:
      min: 1
      max: 10
      step: 1
      distribution: uniform
      num: 1

    dial_noise_scale:
      min: 0.00001
      max: 0.1
      distribution: loguniform
      num: 2

    dial_epsilon:
      min: 0.001
      max: 0.01
      distribution: loguniform
      num: 2


diva_mldg:
  aname: diva
  trainer: mldg
  shared:
    - gamma_y
    - gamma_d
    - gamma_reg


hduva_mldg:
  aname: hduva
  trainer: mldg
  shared:
    - gamma_y
    - zy_dim
    - gamma_reg
