# test benchmark config.

test_domains:
  - acevedo
  - mll
  - matek

output_dir: zoutput/benchmarks/blood
# number of hyperparameter samples per task.
# Thus, the total runs of each task are given
# by len(domains) * num_param_samples * num_seeds (see below)
num_param_samples: 8
sampling_seed: 0

startseed: 0
endseed: 5  # currently included



domainlab_args:
  # Domainlab arguments passed to each task.
  # task specific arguments take precedence.
  ## dataset
  tpath: examples/tasks/task_blood3.py
  dmem: False
  lr: 5e-5
  epos: 500
  epos_min: 20
  es: 1
  bs: 32
  npath: examples/nets/resnet50domainbed.py
  san_check: True

Shared params:
  num_shared_param_samples: 8
  gamma_y:
    min: 1e4
    max: 2e5
    step: 100
    distribution: loguniform

  zx_dim:
    min: 0
    max: 96
    step: 32
    distribution: uniform
    datatype: int

  zy_dim:
    min: 32
    max: 96
    step: 32
    distribution: uniform
    datatype: int

  zd_dim:
    reference: zy_dim

  gamma_reg:
    min: 0.01
    max: 10
    distribution: loguniform



erm:  # name
  model: erm
