mode: grid

output_dir: zoutput/benchmarks/benchmark_fbopt_pacs_full

sampling_seed: 0

startseed: 0
endseed: 2

test_domains:
  - sketch

domainlab_args:
  tpath: examples/tasks/task_pacs_path_list.py
  dmem: False
  lr: 5e-5
  epos: 200
  es: 5
  bs: 64
  san_check: False
  npath: examples/nets/resnet50domainbed.py
  npath_dom: examples/nets/resnet50domainbed.py
  npath_topic_distrib_img2topic: examples/nets/resnet50domainbed.py
  npath_encoder_sandwich_layer_img2h4zd: examples/nets/resnet50domainbed.py
  exp_shoulder_clip: 10
  mu_clip: 10_000
  coeff_ma: 0.5
  zx_dim: 0
  zy_dim: 64
  zd_dim: 64
  pperm: 0.5


Shared params:
  k_i_gain:
    min: 0.0001
    max: 0.01
    num: 3
    distribution: loguniform

  mu_init:
    min: 0.00001
    max: 0.001
    num: 4
    distribution: loguniform

  pperm:
    min: 0.1
    max: 0.9
    num: 3
    distribution: uniform

  gamma_reg:
    min: 0.01
    max: 1000
    num: 10
    distribution: loguniform

# Test fbopt with different hyperparameter configurations

jigen_fbopt:
  aname: jigen
  init_setpoint_ratio: 0.99
  trainer: fbopt
  shared:
    - k_i_gain
    - mu_init

jigen_feedforward:
  aname: jigen
  trainer: hyperscheduler
  shared:
    - gamma_reg

jigen_fixed_penalty:
  aname: jigen
  trainer: basic
  shared:
    - gamma_reg

erm:
  aname: deepall
