mode: grid

output_dir: zoutput/benchmarks/benchmark_fbopt

sampling_seed: 0
startseed: 0
endseed: 2

test_domains:
  - 3
  - 0


domainlab_args:
  task: mnistcolor10
  tr_d: [1, 2]
  dmem: False
  lr: 0.001
  epos: 500
  es: 100
  bs: 64
  nname: conv_bn_pool_2
  san_check: False
  exp_shoulder_clip: 10
  mu_clip: 10
  coeff_ma: 0.5
  no_tensorboard: False



Shared params:
  ini_setpoint_ratio:
    min: 0.9
    max: 0.99
    num: 3
    step: 0.05
    distribution: uniform

  k_i_gain:
    min: 0.0001
    max: 0.01
    num: 2
    step: 0.0001
    distribution: uniform

  init_mu4beta:
    min: 0.5
    max: 1.0
    num: 3
    step: 0.1
    distribution: uniform

# Test fbopt with different hyperparameter configurations

jigen_fbopt:
  aname: jigen
  trainer: fbopt

  shared:
    - ini_setpoint_ratio
    - k_i_gain
    - init_mu4beta

erm:
  aname: deepall
