# test benchmark config.

test_domains:
  - sketch

output_dir: zoutput/benchmarks/pacs_benchmark
# number of hyperparameter samples per task.
# Thus, the total runs of each task are given
# by len(domains) * num_param_samples * num_seeds (see below)
num_param_samples: 8
sampling_seed: 0

startseed: 0
endseed: 5  # currently included



domainlab_args:
  # Domainlab arguments passed to each task.
  # task specific arguments take precedence.
  ## dataset
  tpath: examples/tasks/task_pacs_path_list.py
  npath: examples/nets/resnet50domainbed.py
  npath_dom: examples/nets/resnet50domainbed.py
  npath_topic_distrib_img2topic: examples/nets/resnet50domainbed.py
  npath_encoder_sandwich_layer_img2h4zd: examples/nets/resnet50domainbed.py
  dmem: False
  lr: 5e-5
  epos: 500
  es: 1
  bs: 32
  san_check: True

erm:  # name
  model: erm


hduva_matchdg:  # name
  model: matchhduva
  zx_dim: 0

  hyperparameters:
    # Same config as diva.
    gamma_y:
      min: 1e4
      max: 2e5
      step: 100
      distribution: loguniform

    zy_dim:
      min: 32
      max: 96
      step: 32
      distribution: uniform

    zd_dim:
      reference: zy_dim


    # Total number of epochs for contrastive loss
    epochs_ctr:
      min: 2
      max: 10
      step: 1
      distribution: uniform

    # factor to magnify cosine similarity
    tau:
      min: 0.01
      max: 1
      distribution: loguniform

    # Number of epochs before updating the match tensor
    epos_per_match_update:
      min: 1
      max: 20
      step: 1
      distribution: uniform

    # penalty weight for matching loss (Lambda in paper)
    gamma_reg:
      min: 0.01
      max: 10
      distribution: loguniform

hduva_dial:
  # Parameters that are fixed for all runs of this task.
  model: hduva
  trainer: dial
  npath: examples/nets/resnet50domainbed.py
  nname_topic_distrib_img2topic: examples/nets/resnet50domainbed.py
  nname_encoder_sandwich_layer_img2h4zd: examples/nets/resnet50domainbed.py
  # specification of parameters that shall vary
  # between runs to analyze the sensitivity
  # of this task w.r.t. these parameters.
  hyperparameters:
    # Each parameter must contain:
    # - distribution (uniform | loguniform | normal | lognormal)
    # - min and max if distribution is uniform or loguniform
    # - mean and std if distribution is normal or lognormal

    # step is optional and defines discrete parameters
    # with the given step size.
    # If min/mean and step are integer valued,
    # the hyperparameter is ensured to be integer valued too.
    # Otherwise, it is a float and rounding errors can occur.
    gamma_y:
      min: 1e4
      max: 2e5
      step: 100
      distribution: loguniform

    gamma_d:
      min: 1e4
      max: 1e6
      step: 10_000
      distribution: loguniform

    zx_dim:
      min: 0
      max: 96
      step: 32
      distribution: uniform

    zy_dim:
      min: 32
      max: 96
      step: 32
      distribution: uniform

    zd_dim:
      reference: zy_dim


    dial_steps_perturb:
      min: 1
      max: 10
      step: 1
      distribution: uniform

    dial_noise_scale:
      min: 0.00001
      max: 0.1
      distribution: loguniform

    dial_epsilon:
      min: 0.001
      max: 0.01
      distribution: loguniform

    gamma_reg:
      min: 0.01
      max: 10
      distribution: loguniform



diva_dial:
  # Parameters that are fixed for all runs of this task.
  model: diva
  trainer: dial
  # specification of parameters that shall vary
  # between runs to analyze the sensitivity
  # of this task w.r.t. these parameters.
  hyperparameters:
    # Each parameter must contain:
    # - distribution (uniform | loguniform | normal | lognormal)
    # - min and max if distribution is uniform or loguniform
    # - mean and std if distribution is normal or lognormal

    # step is optional and defines discrete parameters
    # with the given step size.
    # If min/mean and step are integer valued,
    # the hyperparameter is ensured to be integer valued too.
    # Otherwise, it is a float and rounding errors can occur.
    gamma_y:
      min: 1e4
      max: 2e5
      step: 100
      distribution: loguniform

    gamma_d:
      min: 1e4
      max: 1e6
      step: 10_000
      distribution: loguniform

    zx_dim:
      min: 0
      max: 96
      step: 32
      distribution: uniform

    zy_dim:
      min: 32
      max: 96
      step: 32
      distribution: uniform

    zd_dim:
      reference: zy_dim


    dial_steps_perturb:
      min: 1
      max: 10
      step: 1
      distribution: uniform

    dial_noise_scale:
      min: 0.00001
      max: 0.1
      distribution: loguniform

    dial_epsilon:
      min: 0.001
      max: 0.01
      distribution: loguniform

    gamma_reg:
      min: 0.01
      max: 10
      distribution: loguniform

# Each node containing the model property is considered as a task.
diva_mldg:  # name
  # Parameters that are fixed for all runs of this task.
  model: diva
  trainer: mldg

  # specification of parameters that shall vary
  # between runs to analyze the sensitivity
  # of this task w.r.t. these parameters.
  hyperparameters:
    # Each parameter must contain:
    # - distribution (uniform | loguniform | normal | lognormal)
    # - min and max if distribution is uniform or loguniform
    # - mean and std if distribution is normal or lognormal

    # step is optional and defines discrete parameters
    # with the given step size.
    # If min/mean and step are integer valued,
    # the hyperparameter is ensured to be integer valued too.
    # Otherwise, it is a float and rounding errors can occur.
    gamma_y:
      min: 10e4
      max: 10e6
      step: 1
      distribution: loguniform

    gamma_d:
      min: 1e4
      max: 1e6
      step: 1
      distribution: loguniform


hduva_mldg:  # name
  model: hduva
  trainer: mldg

  hyperparameters:
    gamma_y:
      min: 7e4
      max: 7e6
      step: 1
      distribution: loguniform

    zy_dim:
      min: 32
      max: 128
      step: 4
      distribution: loguniform
