mode: grid

output_dir: zoutput/benchmarks/benchmark_fbopt

sampling_seed: 0
startseed: 0
endseed: 2

test_domains:
  - 0


domainlab_args:
  task: mnistcolor10
  tr_d: [1, 2]
  dmem: False
  lr: 0.001
  epos: 500
  es: 100
  bs: 64
  nname: conv_bn_pool_2
  san_check: False
  exp_shoulder_clip: 10
  mu_clip: 10
  coeff_ma: 0.5
  no_tensorboard: False



Shared params:
  ini_setpoint_ratio:
    min: 0.95
    max: 0.99
    num: 2
    distribution: uniform

  k_i_gain:
    min: 0.0001
    max: 0.01
    num: 2
    step: 0.0001
    distribution: uniform

  mu_init:
    min: 0.001
    max: 0.1
    num: 3
    distribution: loguniform

  pperm:
    min: 0.1
    max: 0.9
    num: 3
    distribution: uniform

# Test fbopt with different hyperparameter configurations

jigen_feedback:
  aname: jigen
  trainer: fbopt

  shared:
    - ini_setpoint_ratio
    - k_i_gain
    - mu_init
    - pperm
    
jigen_feedforward:
  aname: jigen
  trainer: fbopt
  shared:
    - pperm
  
erm:
  aname: deepall
