# test benchmark config.

test_domains:
  - matek
  - acevedo
  - mll

output_dir: zoutput/benchmarks/blood
# number of hyperparameter samples per task.
# Thus, the total runs of each task are given
# by len(domains) * num_param_samples * num_seeds (see below)
num_param_samples: 8
sampling_seed: 0

startseed: 0
endseed: 5  # currently included


Shared params:
    gamma_y:
      min: 1e4
      max: 2e5
      step: 100
      distribution: loguniform

    zx_dim:
      min: 0
      max: 96
      step: 32
      distribution: uniform

    zy_dim:
      min: 32
      max: 96
      step: 32
      distribution: uniform

    zd_dim:
      reference: zy_dim

  # penalty weight for matching loss (Lambda in paper)
    gamma_reg:
      min: 0.01
      max: 10
      distribution: loguniform


domainlab_args:
  # Domainlab arguments passed to each task.
  # task specific arguments take precedence.
  ## dataset
  tpath: examples/tasks/task_blood2.py
  dmem: False
  lr: 5e-5
  epos: 500
  es: 1
  bs: 32
  npath: examples/nets/resnet50domainbed.py
  san_check: True


diva:  # name
  aname: diva
  # set nname_dom = nname when changing nname
  npath_dom: examples/nets/resnet50domainbed.py

  shared:
    - gamma_y
    - zx_dim
    - zy_dim
    - zd_dim

  hyperparameters:
    gamma_d:
      min: 1e4
      max: 1e6
      step: 10_000
      distribution: loguniform


hduva:  # name
  aname: hduva

  npath_topic_distrib_img2topic: examples/nets/resnet50domainbed.py
  npath_encoder_sandwich_layer_img2h4zd: examples/nets/resnet50domainbed.py

  shared:
    - gamma_y
    - zx_dim
    - zy_dim
    - zd_dim


matchdg:  # name
  aname: matchdg

  shared:
    - gamma_reg

  hyperparameters:
    # Total number of epochs for contrastive loss
    epochs_ctr:
      min: 2
      max: 10
      step: 1
      distribution: uniform

    # factor to magnify cosine similarity
    tau:
      min: 0.01
      max: 1
      distribution: loguniform

    # Number of epochs before updating the match tensor
    epos_per_match_update:
      min: 1
      max: 20
      step: 1
      distribution: uniform


jigen:  # name
  aname: jigen
  grid_len: 3
  shared:
    - gamma_reg

  hyperparameters:
    # number of permutations
    nperm:
      distribution: categorical
      values:
        - 30
        - 31
        - 100
      datatype: int

    # probability of permutating the tiles of an image, pperm = 0 -> pure classification
    pperm:
      min: 0.1
      max: 0.5
      distribution: uniform



dann:  # name
  aname: dann
  shared:
    - gamma_reg


deepall:  # name
  aname: deepall


dial: # name
  aname: deepall_dial
  shared:
    - gamma_reg

  hyperparameters:
    dial_steps_perturb:
      min: 1
      max: 10
      step: 1
      distribution: uniform

    dial_noise_scale:
      min: 0.00001
      max: 0.1
      distribution: loguniform

    dial_epsilon:
      min: 0.001
      max: 0.01
      distribution: loguniform


mldg:  # name
  aname: deepallmldg
  shared: gamma_reg



