# test benchmark config.
mode: grid
test_domains:
  - 3
  - 0

output_dir: zoutput/benchmarks/mnist_benchmark
# number of hyperparameter samples per task.
# Thus, the total runs of each task are given
# by len(domains) * num_param_samples * num_seeds (see below)
num_param_samples: 8
sampling_seed: 0

startseed: 0
endseed: 2  # currently included


Shared params:
    gamma_y:
      min: 1e4
      max: 1e5
      step: 100
      distribution: loguniform
      num: 2

    zy_dim:
      min: 32
      max: 96
      step: 32
      distribution: uniform
      num: 2


domainlab_args:
  # Domainlab arguments passed to each task.
  # task specific arguments take precedence.
  ## dataset
  task: mnistcolor10
  tr_d: [1, 2, 4]
  dmem: False
  lr: 0.001
  epos: 50
  es: 5
  bs: 64
  nname: conv_bn_pool_2
  san_check: True


Task1:  # name
  aname: diva
  shared:
    - gamma_y
    - zy_dim
  nname_dom: conv_bn_pool_2

  hyperparameters:
    gamma_d:
      min: 1e4
      max: 1e6
      step: 10_000
      distribution: loguniform
      num: 2

    zx_dim:
      min: 0
      max: 96
      step: 32
      distribution: uniform
      num: 2

    zd_dim:
      reference: zy_dim

Task2:  # name
  aname: hduva

  nname_topic_distrib_img2topic: conv_bn_pool_2
  nname_encoder_sandwich_layer_img2h4zd: conv_bn_pool_2
  shared:
    - gamma_y
    - zy_dim
  zx_dim: 0
  hyperparameters:
    zd_dim:
      reference: zy_dim
