mode: grid

output_dir: zoutput/benchmarks/benchmark_fbopt

sampling_seed: 0
startseed: 0
endseed: 4

test_domains:
  - 0


domainlab_args:
  task: mnistcolor10
  tr_d: [1, 2]
  dmem: False
  lr: 0.001
  epos: 500
  es: 100
  bs: 64
  nname: conv_bn_pool_2
  san_check: False
  exp_shoulder_clip: 10
  mu_clip: 10
  coeff_ma: 0.5
  no_tensorboard: False
  pperm: 0.5



Shared params:
  ini_setpoint_ratio:
    min: 0.95
    max: 0.99
    num: 2
    distribution: uniform

  k_i_gain:
    min: 0.0001
    max: 0.01
    num: 2
    step: 0.0001
    distribution: uniform

  mu_init:
    min: 0.00001
    max: 0.0001
    num: 3
    distribution: loguniform

  gamma_reg:
    min: 0.01
    max: 10
    num: 10
    distribution: loguniform



# Test fbopt with different hyperparameter configurations

jigen_feedback:
  aname: jigen
  trainer: fbopt
  ini_setpoint_ratio: 0.99
  shared:
    - k_i_gain
    - mu_init
    
jigen_feedforward:
  aname: jigen
  trainer: hyperscheduler
  shared:
    - gamma_reg

jigen_fixed_penalty:
  aname: jigen
  trainer: basic
  shared:
    - gamma_reg

erm:
  aname: deepall
