# test benchmark config.

mode: grid

test_domains:
  - sketch

output_dir: zoutput/benchmarks/pacs_benchmark_grid

startseed: 0
endseed: 1  # currently included


domainlab_args:
  tpath: examples/tasks/task_pacs_path_list.py
  dmem: False
  lr: 5e-5
  epos: 500
  es: 1
  bs: 32
  npath: examples/nets/resnet50domainbed.py
  npath_encoder_x2topic_h: examples/nets/resnet50domainbed.py
  npath_encoder_sandwich_x2h4zd: examples/nets/resnet50domainbed.py
  san_check: False


Shared params:
  gamma_reg:
    min: 0.01
    max: 10
    step: 0.1
    distribution: loguniform
    num: 3


jigen:  # name
  model: jigen
  shared:
    - gamma_reg

  hyperparameters:
    # probability of permutating the tiles of an image, pperm = 0 -> pure classification
    pperm:
      min: 0.7
      max: 1
      step: 0.1
      distribution: uniform
      num: 3


erm:
  model: erm
