mode: grid

output_dir: zoutput/benchmarks/pacs_jigen_fbopt_alone

sampling_seed: 0

startseed: 0
endseed: 3

test_domains:
  - sketch

domainlab_args:
  tpath: examples/tasks/task_pacs_path_list.py
  dmem: False
  lr: 5e-5
  epos: 500
  epos_min: 50
  force_setpoint_change_once: True
  es: 1
  bs: 64
  san_check: False
  npath: examples/nets/resnet50domainbed.py
  npath_dom: examples/nets/resnet50domainbed.py
  npath_topic_distrib_img2topic: examples/nets/resnet50domainbed.py
  npath_encoder_sandwich_layer_img2h4zd: examples/nets/resnet50domainbed.py
  zx_dim: 0
  zy_dim: 64
  zd_dim: 64
  pperm: 0.1  
  # pperm correspond to 1-bias_wholeimage in https://github.com/fmcarlucci/JigenDG


Shared params:
  k_i_gain:
    min: 0.0001
    max: 0.01
    num: 3
    distribution: loguniform

  k_i_gain_ratio:
    min: 0.1
    max: 1
    num: 5
    distribution: uniform

  mu_init:
    min: 0.000001
    max: 0.00005
    num: 3
    distribution: loguniform

  pperm:
    min: 0.1
    max: 0.9
    num: 3
    distribution: uniform

  gamma_reg:
    min: 0.01
    max: 10_000
    num: 10
    distribution: loguniform

  coeff_ma_setpoint:
    distribution: categorical
    datatype: float
    values:
      - 0.0
      - 0.5
      - 0.9

  coeff_ma_output_state:
    distribution: categorical
    datatype: float
    values:
      - 0.0
      - 0.5
      - 0.9

# Test fbopt with different hyperparameter configurations

jigen_feedback:
  model: jigen
  trainer: fbopt
  ini_setpoint_ratio: 0.99
  mu_init: 1e-6

  shared:
    - k_i_gain_ratio
    - coeff_ma_output_state
    - coeff_ma_setpoint
