mode: grid

output_dir: zoutput/benchmarks/benchmark_fbopt_pacs_full

sampling_seed: 0

startseed: 0
endseed: 5

test_domains:
  - sketch

domainlab_args:
  tpath: examples/tasks/task_pacs_path_list.py
  dmem: False
  lr: 5e-5
  epos: 200
  epos_min: 20
  es: 1
  bs: 64
  san_check: False
  npath: examples/nets/resnet50domainbed.py
  npath_dom: examples/nets/resnet50domainbed.py
  npath_encoder_x2topic_h: examples/nets/resnet50domainbed.py
  npath_encoder_sandwich_x2h4zd: examples/nets/resnet50domainbed.py
  zx_dim: 0
  zy_dim: 64
  zd_dim: 64
  pperm: 0.5


Shared params:
  k_i_gain:
    min: 0.0001
    max: 0.01
    num: 2
    distribution: loguniform

  mu_init:
    min: 0.000001
    max: 0.00005
    num: 2
    distribution: loguniform

  pperm:
    min: 0.1
    max: 0.9
    num: 3
    distribution: uniform

  gamma_reg:
    min: 0.01
    max: 10_000
    num: 4
    distribution: loguniform

  mu_clip:
    distribution: categorical
    datatype: float
    values:
      - 1
      - 10
      - 100
      - 1000

# Test fbopt with different hyperparameter configurations

jigen_feedback:
  model: jigen
  trainer: fbopt
  ini_setpoint_ratio: 0.99
  mu_init: 0.000001
  shared:
    - k_i_gain
    - mu_clip

jigen_feedforward:
  model: jigen
  trainer: hyperscheduler
  shared:
    - gamma_reg

jigen_fixed_penalty:
  model: jigen
  trainer: basic
  shared:
    - gamma_reg

erm:
  model: erm
