mode: grid

output_dir: zoutput/benchmarks/benchmark_fbopt_fishr_erm_pacs

sampling_seed: 0
startseed: 0
endseed: 0

test_domains:
  - sketch

domainlab_args:
  tpath: examples/tasks/task_pacs_aug.py
  dmem: False
  lr: 5e-5
  epos: 10
  epos_min: 2
  es: 5
  bs: 32
  san_check: False
  nname: alexnet
  nname_dom: alexnet
  zx_dim: 0
  zy_dim: 64
  zd_dim: 64




Shared params:
  ini_setpoint_ratio:
    min: 0.5
    max: 0.99
    num: 2
    step: 0.05
    distribution: uniform

  k_i_gain:
    min: 0.0001
    max: 0.01
    num: 2
    step: 0.0001
    distribution: uniform

  gamma_reg:
    min: 0.01
    max: 1e4
    num: 3
    distribution: loguniform


# Test fbopt with different hyperparameter configurations

fbopt_fishr_erm:
  model: erm
  trainer: fbopt_fishr
  shared:
    - ini_setpoint_ratio
    - k_i_gain
    - gamma_reg

fishr_erm:
  model: erm
  trainer: fishr
  shared:
    - gamma_reg
