mode: grid

output_dir: zoutput/benchmarks/pacs_diva_fbopt_and_others

sampling_seed: 0

startseed: 0
endseed: 2

test_domains:
  - sketch

domainlab_args:
  tpath: examples/tasks/task_pacs_path_list.py
  dmem: False
  lr: 5e-5
  epos: 200
  es: 10
  bs: 64
  san_check: True
  npath: examples/nets/resnet50domainbed.py
  npath_dom: examples/nets/resnet50domainbed.py
  npath_topic_distrib_img2topic: examples/nets/resnet50domainbed.py
  npath_encoder_sandwich_layer_img2h4zd: examples/nets/resnet50domainbed.py
  exp_shoulder_clip: 10
  mu_clip: 1000_000
  coeff_ma: 0.5
  zx_dim: 0
  zy_dim: 64
  zd_dim: 64




Shared params:
  ini_setpoint_ratio:
    min: 0.9
    max: 0.99
    num: 3
    distribution: uniform

  k_i_gain:
    min: 0.0001
    max: 0.01
    num: 3
    distribution: uniform

  mu_init:
    min: 0.000001
    max: 0.9
    num: 3
    distribution: loguniform

  gamma_y:
    min: 1.0
    max: 1e6
    step: 100
    num: 3
    distribution: loguniform

  gamma_d:
    min: 1.0
    max: 1e6
    step: 100
    num: 3
    distribution: loguniform



# Test fbopt with different hyperparameter configurations

diva_fbopt_full:
  aname: diva
  trainer: fbopt
  str_diva_multiplier_type: gammad_recon
  gamma_y: 1.0
  ini_setpoint_ratio: 0.99
  shared:
    - k_i_gain
    - mu_init

diva_feedforward_full:
  aname: diva
  trainer: hyperscheduler
  str_diva_multiplier_type: gammad_recon
  gamma_y: 1.0
  shared:
    - gamma_d

diva_default:
  aname: diva
  trainer: hyperscheduler
  str_diva_multiplier_type: default
  shared:
    - gamma_d
    - gamma_y

diva_fixed_penalty:
  aname: diva
  trainer: basic
  str_diva_multiplier_type: default
  shared:
    - gamma_d
    - gamma_y

erm:
  aname: deepall
