mode: grid

output_dir: zoutput/benchmarks/pacs_jigen_fbopt_baselines

sampling_seed: 0

startseed: 0
endseed: 4

test_domains:
  - sketch

domainlab_args:
  tpath: examples/tasks/task_pacs_aug_noflip.py
  dmem: False
  lr: 5e-5
  epos: 500
  epos_min: 100
  es: 1
  bs: 64
  san_check: True
  npath: examples/nets/resnet50domainbed.py
  npath_dom: examples/nets/resnet50domainbed.py
  npath_encoder_x2topic_h: examples/nets/resnet50domainbed.py
  npath_encoder_sandwich_x2h4zd: examples/nets/resnet50domainbed.py
  zx_dim: 0
  zy_dim: 64
  zd_dim: 64


Shared params:
  k_i_gain:
    min: 0.0001
    max: 0.01
    num: 3
    distribution: loguniform

  mu_init:
    min: 0.000001
    max: 0.00005
    num: 3
    distribution: loguniform

  pperm:
    min: 0.1
    max: 0.9
    num: 3
    distribution: uniform

  gamma_reg:
    min: 0.01
    max: 10
    num: 5
    distribution: loguniform

# Test fbopt with different hyperparameter configurations

    
jigen_feedforward:
  model: jigen
  trainer: hyperscheduler
  shared:
    - gamma_reg
    - pperm

jigen_fixed_penalty:
  model: jigen
  trainer: basic
  shared:
    - gamma_reg
    - pperm

erm:
  model: erm
