mode: grid

output_dir: zoutput/benchmarks/pacs_diva_others

sampling_seed: 0

startseed: 0
endseed: 6
test_domains: - sketch

domainlab_args:
  tpath: examples/tasks/task_pacs_aug.py
  dmem: False
  lr: 5e-5
  epos: 500
  epos_min: 200
  es: 5
  bs: 32
  san_check: False
  npath: examples/nets/resnet50domainbed.py
  npath_dom: examples/nets/resnet50domainbed.py
  zx_dim: 0
  zy_dim: 64
  zd_dim: 64




Shared params:

  gamma_y:
    min: 1.0
    max: 1e6
    step: 100
    num: 3
    distribution: loguniform

  gamma_d:
    min: 1.0
    max: 1e6
    step: 100
    num: 3
    distribution: loguniform


diva_feedforward_full:
  model: diva
  trainer: hyperscheduler
  str_diva_multiplier_type: gammad_recon
  shared:
    - gamma_d
    - gamma_y

diva_default:
  model: diva
  trainer: hyperscheduler
  str_diva_multiplier_type: default
  shared:
    - gamma_d
    - gamma_y

diva_fixed_penalty:
  model: diva
  trainer: basic
  str_diva_multiplier_type: default
  shared:
    - gamma_d
    - gamma_y
