cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --partition=gpu_p
    --qos=gpu
    --gres=gpu:1
    --nice=10000
    -c 2
    --mem=60G
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
default-resources:
  - partition=gpu_p
  - qos=gpu
  - mem_mb=60000
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
latency-wait: 60
jobs: 500
keep-going: True
printshellcmds: True
scheduler: greedy
use-conda: True
