# This yaml file has been adapted from https://github.com/jdblischak/smk-simple-slurm
cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --partition=gpu_p 
    --qos=gpu 
    --gres=gpu:1 
    --nice=10000 
    -t 48:00:00
    -c 2 
    --mem=100G 
    --job-name=smk-{rule}-{wildcards} 
    --output=logs/{rule}/{rule}-{wildcards}-%j.out 
    --error=logs/{rule}/{rule}-{wildcards}-%j.err
default-resources:
  - partition=gpu_p 
  - qos=gpu 
  - mem_mb=100000 
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
latency-wait: 60
jobs: 500
keep-going: True
printshellcmds: True
scheduler: greedy
use-conda: True
