# only entries related to parameter sampling
num_param_samples: 30

# currently, everything which contains the aname property is considered as a task.
Task1:  # name
  aname: Algo1
  p1:
    authorschoice: 1.5
    distribution: uniform    # uniform | loguniform | normal | lognormal
    min: 1
    max: 2
    step: 0    # anything > 0 for discrete variables, 0 for continuous ones.

  p2:
    authorschoice: 3
    distribution: normal
    min: 0
    max: 5
    step: 1 # integer valued

  p3:
    authorschoice: 1e-3
    min: 1e-6
    max: 1
    distribution: loguniform
    step: 0


  constraints:
    - "p1 < p2"    # any valid Python code evaluating to bool, variables are having the name from above.
    - "p3 < p2"

Task2:  # name
  aname: Algo2

  p1:
    authorschoice: 5
    min: 1
    max: 1e6
    step: 1
    distribution: loguniform
