name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-shell
        python setup.py install
    - name: Install Python Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --with dev
    - name: test if api works
      run: poetry run python examples/api/jigen_dann_transformer.py
    - name: Generate coverage report
      run: rm -r zoutput && poetry run pytest --cov=domainlab tests/ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: unittests
        env_vars: OS,PYTHON
        fail_ci_if_error: true
      env:
        CODECOV_TOKEN: 02ecb3ac-b7ce-4ea4-90a2-961c3d1a1030
    - name: check if readme yaml works
      run: rm -r zoutput && python main_out.py -c ./examples/conf/vlcs_diva_mldg_dial.yaml
    - name: test if examples in markdown works
      run: bash -x -v scripts/ci_run_examples.sh
    - name: test if benchmark works
      run: | 
          pip install snakemake==7.32.0 && pip install pulp==2.7.0
          echo "insert a shebang line (#!/bin/bash -x -v) at the beginning of the bash script"
          sed -i '1s/^/#!\/bin\/bash -x -v\n/' run_benchmark_standalone.sh
          bash -x -v run_benchmark_standalone.sh examples/benchmark/demo_shared_hyper_grid.yaml
          cat zoutput/benchmarks/mnist_benchmark_grid/hyperparameters.csv
          cat zoutput/benchmarks/mnist_benchmark_grid/results.csv
