name: CI

on:
  push:
    branches: master
  pull_request:
    branches: fbopt
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-shell
        python setup.py install
    - name: Generate coverage report
      run: pytest --cov=domainlab tests/ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: unittests
        env_vars: OS,PYTHON
        fail_ci_if_error: true
    - name: test if examples in markdown works
      run: bash -x -v ci_run_examples.sh
    - name: test if benchmark works
      run: bash -x -v run_benchmark_standalone.sh examples/benchmark/benchmark_mnist_shared_hyper_grid.yaml
